name: build

on:
    pull_request: ~
    push: ~

jobs:
    cs-fixer:
        runs-on: ubuntu-22.04
        name: PHP-CS-Fixer
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Fix CS
              uses: docker://oskarstark/php-cs-fixer-ga
    tests:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                include:
                    - description: 'lowest'
                      php: '8.1'
                      composer_option: '--prefer-lowest'
                    - description: '8.2'
                      php: '8.2'
                    - description: 'latest'
                      php: '8.3'
        name: PHP ${{ matrix.php }} tests
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with: 
                  path: ~/.composer/cache/files
                  key: ${{ matrix.php }}-${{ matrix.composer_option }} 
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
            - run: composer update --no-interaction --no-progress --ansi ${{ matrix.composer_option }}
            - run: bin/phpunit

